version: '3'
services:
  app:
    build: ./
    working_dir: /app
    volumes:
      - ../:/app
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined